apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - name: simpple-consumer
        image: simple-consumer
        ports:
          - containerPort: 8090
        imagePullPolicy: Never
        args: ["java", "-jar", "target/simple-consumer-1.0.0-jar-with-dependencies.jar", "kafka-cluster-kafka-bootstrap.keda-sample:9092", "testSample", "messages", "Bob", "true"]