apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaler
  labels:
    deploymentName: consumer-service
spec:
  scaleType: job
  jobTargetRef:
    parallelism: 1 # [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
    completions: 1
    activeDeadlineSeconds: 600
    backoffLimit: 6
    template:
      spec:
        containers:
          - name: simple-consumer
            image: simple-consumer
            ports:
              - containerPort: 8090
            imagePullPolicy: Never
            args: ["java", "-jar", "target/simple-consumer-1.0.0-jar-with-dependencies.jar", "kafka-cluster-kafka-bootstrap.keda-sample:9092", "testSample", "messages", "Bob", "true"]
        restartPolicy: Never
  pollingInterval: 1
  cooldownPeriod:  30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        topic: messages
        brokerList: kafka-cluster-kafka-bootstrap.keda-sample:9092
        consumerGroup: testSample
        lagThreshold: '5'