apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
type: Opaque
data:
  username: 'scaler-user' # Convert this to base64
  authMode: 'sasl_scram_sha512' # Convert this to base64
---
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-sample-trigger-auth
spec:
  secretTargetRef:
  - parameter: password
    name: scaler-user
    key: password
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: authMode
    name: keda-kafka-secrets
    key: authMode
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaler
  labels:
    deploymentName: consumer-service
spec:
  scaleTargetRef:
    deploymentName: consumer-service
  pollingInterval: 1
  cooldownPeriod:  30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        topic: messages
        brokerList: kafka-cluster-kafka-bootstrap.keda-sample:9092
        consumerGroup: testSample
        lagThreshold: '5'
      authenticationRef:
        name: keda-sample-trigger-auth